# fly.toml app configuration file generated for kero-bot on 2025-10-13T05:37:03Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'kero-bot'
primary_region = 'nrt'

[build]
  dockerfile = 'Dockerfile'

[processes]
  bot = 'npm run start'

[env]
  NODE_ENV = 'production'

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
